### ISSUE TITLE
Window Generators - Reverse direction of knobs for time parameters

### ISSUE THREAD

**Issue by Kwurqx** [nullJaX/vcvrack-patchable-devices#1]
Hi,

I checked out your Patchable Devices modules in VCV Rack. Great stuff.

The direction of Windows Generators knobs are unintuitive to me. Cuurently: longer times to the right and shorter times to the left. 

My GUI intuition tells me: shorter times to the left and longer times to the right.

**Comment by nullJaX** [comment]
Hi,

The module was heavily inspired by Serge Extended ADSR. I understand the confusion, however this starts to make sense once you start looping/cycling the module.
Time parameters have an exponential response (as well as their control voltage inputs) and, in looping mode, the user can control the frequency (or the speed) of the cycle the same way as they would do for an oscillator/filter/slew limiter.

During the implementation, it made more sense to keep it this way (knobs and CV inputs acting just like V/Octave inputs in Oscillators) rather than introducing more confusion with different directions of the CV and knobs, etc.
Even if I used different naming for these parameters (ie. 'Rate' or 'Frequency' instead of 'Time'), there would have been a problem with units (**Volts / seconds** or **Hz** are quite unusable if you use this module as the Envelope Generator).

Thanks for a feedback.
