### ISSUE TITLE
Window Generators - Time values set/displayed for envelope/function segments are not the actual times

### ISSUE THREAD

**Issue by Kwurqx** [nullJaX/vcvrack-patchable-devices#2]
Hi,

I checked out your Patchable Devices modules in VCV Rack. Great stuff.

Time values set/displayed for envelope/function segments are not the actual times. Also, they seem to be relative to adjectent levels.

Suggest to find an algortithm that respects the actual time as set, also independent of values for other knobs.

**Comment by nullJaX** [comment]
Hey,

The stage times are not dependent on each other and satisfy the values displayed in tool-tips as long as the Shape knob is centered (Linear).
I took the module and compared with a pulse generator on the scope.
For T1 and T2 gates, it shows correct length.
Since both T3 and T4 interact with the Sustain phase, the values displayed assume the situation when the sustain is 100% (hence, they are shorter on the scope if the sustain is lower).
When the sustain is lower than 100% and the 'slew rate' stays the same (this module consists of just 4 slew limiter cells, one of which is the primary one - ADASR), it means that the sustain level will be reached faster.
