### ISSUE TITLE
Window Generators - Behaviour when Sustain at 0 (zero)

### ISSUE THREAD

**Issue by Kwurqx** [nullJaX/vcvrack-patchable-devices#5]
Hi,

I tried out your Patchable Devices modules in VCV Rack. Great stuff!

Not sure about the behaviour of Window Generators when Sustain is at 0 (zero). It seems to mess up the staging? I noticed that gating/triggering would no longer give me an envelope/funtion when sustain is set to 0? Maybe this is related to the relative nature of the stages times/levels?

I was actually trying to set up AD and AR envelopes. Maybe I just don't get it (yet). Maybe I was using the wrong segments config (AHDSR with no H and no S or R).  Maybe Window Generators can handle this fine with some explanation/instruction.

**Comment by nullJaX** [comment]
Hey,

For **Attack-Decay** envelope shape, you should use **DAHR** output:
- Set T1 (Delay Time) and T3 (Hold Time) to the lowest value possible
- T2 will control the Attack
- T4 will control the Decay
- Sustain is not processed in DAHR envelope

For **Attack-(Sustain)-Release** envelope shape, you can use either **DADSR** or **AHDSR** (**ADASR** will always introduce a positive spike caused by T1 & T2). Make sure to set the Sustain level to maximum. T4 will always control the Release time. For the other time parameters:
- **DADSR**:
  - T1 and T3 set to minimum
  - T2 controls the Attack
- **AHDSR**:
  - T2 and T3 set to minimum
  - T1 controls the Attack

**Note:** The sustain phase only checks if the gate signal is still active. You can also achieve Attack-Decay when using Trigger input instead of a Gate input.
