### ISSUE TITLE
Dual Integrator - As a VCA it does not go to 0 (silence) via CV

### ISSUE THREAD

**Issue by Kwurqx** [nullJaX/vcvrack-patchable-devices#6]
Hi,

I tried out your Patchable Devices modules in VCV Rack. Great stuff!

I tried to use the Dual integrator as a VCA (and/or filter/Low Pass Gate). It seems that it will not completely go down to 0 V / silence via CV?

**Comment by nullJaX** [comment]
Hi,
Yes, you are correct, it will not silence the signal completely. 

Since each cell in its core consists of just a slew limiter, its primary functionality is to limit the rate of change (positive and negative) for the incoming signal. This is the exact behavior when you try to use a low pass filter to attenuate the signal - there will always be some kind of a bleed-through (when the signal has high amplitude and/or low frequency) and while reducing the cutoff frequency, you will loose high frequencies first. Even if you zoom in the waveform on the scope, you will be able to see some fluctuations.

There is one workaround though: You can use `HOLD` gate input to mute the signal (this sets the maximum allowed rate of change to 0V/s). However, note that this will freeze entirely the signal, leaving it most probably nowhere near 0 Volts.

Thanks for a feedback.
